import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [

        ]),
      ),
    );
  }
}

class extends StatelessWidget {
@override
Widget build(BuildContext context) {
return Column(
children: [
Container(
width: 430,
height: 932,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(color: Colors.white),
child: Stack(
children: [
Positioned(
left: 66,
top: 167,
child: Container(
width: 297,
height: 355,
child: Stack(
children: [
Positioned(
left: 63,
top: 106,
child: Text(
'ai가 조합해주는 영양제를\n하루 한포 먹기 쉽게!!',
textAlign: TextAlign.center,
style: TextStyle(
color: Color(0x99323232),
fontSize: 16,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
Positioned(
left: 0,
top: 0,
child: Text.rich(
TextSpan(
children: [
TextSpan(
text: '간단',
style: TextStyle(
color: Colors.black,
fontSize: 40,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 0,
),
),
TextSpan(
text: '하게',
style: TextStyle(
color: Colors.black.withOpacity(0.550000011920929),
fontSize: 35,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
TextSpan(
text: ' 건강',
style: TextStyle(
color: Colors.black,
fontSize: 40,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 0,
),
),
TextSpan(
text: '하자',
style: TextStyle(
color: Color(0xFF737373),
fontSize: 35,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
TextSpan(
text: ',\n',
style: TextStyle(
color: Color(0xFF737373),
fontSize: 40,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
TextSpan(
text: '이지필',
style: TextStyle(
color: Colors.black,
fontSize: 40,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 0,
),
),
],
),
textAlign: TextAlign.center,
),
),
Positioned(
left: 56,
top: 171,
child: Text(
'💊',
style: TextStyle(
color: Colors.black,
fontSize: 184,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
],
),
),
),
Positioned(
left: 179,
top: 567,
child: Container(
height: 14,
child: Stack(
children: [
Positioned(
left: 0,
top: 0,
child: Container(
width: 14,
height: 14,
decoration: ShapeDecoration(
color: Color(0xFF1E1E1E),
shape: OvalBorder(),
),
),
),
Positioned(
left: 29,
top: 0,
child: Container(
width: 14,
height: 14,
decoration: ShapeDecoration(
color: Color(0xFFD9D9D9),
shape: OvalBorder(),
),
),
),
Positioned(
left: 58,
top: 0,
child: Container(
width: 14,
height: 14,
decoration: ShapeDecoration(
color: Color(0xFFD9D9D9),
shape: OvalBorder(),
),
),
),
],
),
),
),
Positioned(
left: 62,
top: 671,
child: Container(
width: 305,
height: 51,
child: Stack(
children: [
Positioned(
left: 0,
top: 0,
child: Container(
width: 305,
height: 51,
decoration: ShapeDecoration(
color: Color(0xFFFEE201),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(25.50),
),
),
),
),
Positioned(
left: 17,
top: 11,
child: Container(
width: 31,
height: 30,
decoration: BoxDecoration(
image: DecorationImage(
image: NetworkImage("https://via.placeholder.com/31x30"),
fit: BoxFit.fill,
),
),
),
),
Positioned(
left: 88,
top: 17,
child: Text(
'카카오톡으로 로그인',
style: TextStyle(
color: Colors.black,
fontSize: 15,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
],
),
),
),
Positioned(
left: 62,
top: 741,
child: Container(
width: 305,
height: 51,
child: Stack(
children: [
Positioned(
left: 0,
top: 0,
child: Container(
width: 305,
height: 51,
decoration: ShapeDecoration(
color: Color(0xFF04C73C),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(25.50),
),
),
),
),
Positioned(
left: 17,
top: 10,
child: Container(
width: 33,
height: 32,
decoration: BoxDecoration(
image: DecorationImage(
image: NetworkImage("https://via.placeholder.com/33x32"),
fit: BoxFit.fill,
),
),
),
),
Positioned(
left: 102,
top: 17,
child: Text(
'네이버로 로그인',
style: TextStyle(
color: Colors.white,
fontSize: 15,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
],
),
),
),
Positioned(
left: 148,
top: 811,
child: Text(
'휴대폰 번호로 로그인 ',
style: TextStyle(
color: Color(0x7C1E1E1E),
fontSize: 15,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
textDecoration: TextDecoration.underline,
height: 0,
),
),
),
Positioned(
left: 21,
top: 73,
child: Container(
width: 54,
height: 54,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
child: Stack(children: [
,
]),
),
),
],
),
),
Container(
width: 430,
height: 932,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(color: Colors.white),
child: Stack(
children: [
Positioned(
left: 27,
top: 89,
child: Text(
' ',
style: TextStyle(
color: Colors.black,
fontSize: 8,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
Positioned(
left: 0,
top: 126,
child: Container(
width: 459,
height: 627,
decoration: BoxDecoration(
image: DecorationImage(
image: NetworkImage("https://via.placeholder.com/459x627"),
fit: BoxFit.fill,
),
),
),
),
Positioned(
left: 341,
top: 145,
child: Container(
width: 89,
height: 37,
decoration: BoxDecoration(color: Colors.white),
),
),
Positioned(
left: 21,
top: 73,
child: Container(
width: 54,
height: 54,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
child: Stack(children: [
,
]),
),
),
],
),
),
Container(
width: 430,
height: 932,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(color: Colors.white),
child: Stack(
children: [
Positioned(
left: 27,
top: 89,
child: Text(
' ',
style: TextStyle(
color: Colors.black,
fontSize: 8,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
Positioned(
left: -4,
top: 89,
child: Container(
width: 434,
height: 518,
decoration: BoxDecoration(
image: DecorationImage(
image: NetworkImage("https://via.placeholder.com/434x518"),
fit: BoxFit.fill,
),
),
),
),
Positioned(
left: 17,
top: 73,
child: Container(
width: 54,
height: 54,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
child: Stack(children: [
,
]),
),
),
],
),
),
Container(
width: 430,
height: 932,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(color: Colors.white),
child: Stack(
children: [
Positioned(
left: 27,
top: 89,
child: Text(
' ',
style: TextStyle(
color: Colors.black,
fontSize: 8,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
Positioned(
left: 32,
top: 166,
child: Text(
'휴대폰 번호로 로그인 ',
style: TextStyle(
color: Colors.black,
fontSize: 30,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 0,
),
),
),
Positioned(
left: 289,
top: 84,
child: Container(
width: 100,
height: 36,
decoration: ShapeDecoration(
color: Color(0xFF41A49D),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(11),
),
),
),
),
Positioned(
left: 305,
top: 91,
child: Text(
'회원가입',
style: TextStyle(
color: Colors.white,
fontSize: 18,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
Positioned(
left: 32,
top: 315,
child: Container(
width: 357,
height: 51,
decoration: ShapeDecoration(
color: Colors.white,
shape: RoundedRectangleBorder(
side: BorderSide(
width: 1,
color: Colors.black.withOpacity(0.3199999928474426),
),
borderRadius: BorderRadius.circular(12),
),
),
),
),
Positioned(
left: 188,
top: 450,
child: Text(
'로그인 ',
style: TextStyle(
color: Colors.white,
fontSize: 19,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 0,
),
),
),
Positioned(
left: 54,
top: 279,
child: Text(
'번호',
style: TextStyle(
color: Colors.black.withOpacity(0.36000001430511475),
fontSize: 17,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 0,
),
),
),
Positioned(
left: 54,
top: 376,
child: Text(
'대/소문자,숫자,특수문자 8자리 이상',
style: TextStyle(
color: Colors.black.withOpacity(0.36000001430511475),
fontSize: 17,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 0,
),
),
),
Positioned(
left: 32,
top: 329,
child: SizedBox(
width: 82,
height: 23,
child: Text(
'비밀번호',
style: TextStyle(
color: Colors.black,
fontSize: 17,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
),
Positioned(
left: 34,
top: 235,
child: SizedBox(
width: 104,
height: 20,
child: Text(
'휴대폰 번호',
style: TextStyle(
color: Colors.black,
fontSize: 17,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
),
Positioned(
left: 106,
top: 291,
child: Container(
width: 100,
height: 100,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
),
),
Positioned(
left: 58,
top: 543,
child: Container(
width: 305,
height: 51,
child: Stack(
children: [
Positioned(
left: 0,
top: 0,
child: Container(
width: 305,
height: 51,
decoration: ShapeDecoration(
color: Color(0xFFFEE201),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(25.50),
),
),
),
),
Positioned(
left: 17,
top: 11,
child: Container(
width: 31,
height: 30,
decoration: BoxDecoration(
image: DecorationImage(
image: NetworkImage("https://via.placeholder.com/31x30"),
fit: BoxFit.fill,
),
),
),
),
Positioned(
left: 88,
top: 17,
child: Text(
'카카오톡으로 로그인',
style: TextStyle(
color: Colors.black,
fontSize: 15,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
],
),
),
),
Positioned(
left: 58,
top: 618,
child: Container(
width: 305,
height: 51,
child: Stack(
children: [
Positioned(
left: 0,
top: 0,
child: Container(
width: 305,
height: 51,
decoration: ShapeDecoration(
color: Color(0xFF04C73C),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(25.50),
),
),
),
),
Positioned(
left: 17,
top: 10,
child: Container(
width: 33,
height: 32,
decoration: BoxDecoration(
image: DecorationImage(
image: NetworkImage("https://via.placeholder.com/33x32"),
fit: BoxFit.fill,
),
),
),
),
Positioned(
left: 102,
top: 17,
child: Text(
'네이버로 로그인',
style: TextStyle(
color: Colors.white,
fontSize: 15,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
],
),
),
),
Positioned(
left: 187,
top: 79,
child: Container(
width: 47,
height: 41,
decoration: BoxDecoration(
image: DecorationImage(
image: NetworkImage("https://via.placeholder.com/47x41"),
fit: BoxFit.fill,
),
),
),
),
],
),
),
Container(
width: 430,
height: 932,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(color: Colors.white),
child: Stack(
children: [
Positioned(
left: 27,
top: 89,
child: Text(
' ',
style: TextStyle(
color: Colors.black,
fontSize: 8,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
Positioned(
left: 41,
top: 166,
child: Text(
'휴대폰 번호로 회원가입 ',
style: TextStyle(
color: Colors.black,
fontSize: 30,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 0,
),
),
),
Positioned(
left: 41,
top: 315,
child: Container(
width: 357,
height: 51,
decoration: ShapeDecoration(
color: Colors.white,
shape: RoundedRectangleBorder(
side: BorderSide(
width: 1,
color: Colors.black.withOpacity(0.3199999928474426),
),
borderRadius: BorderRadius.circular(12),
),
),
),
),
Positioned(
left: 185,
top: 558,
child: Text(
'회원가입',
style: TextStyle(
color: Colors.white,
fontSize: 19,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 0,
),
),
),
Positioned(
left: 63,
top: 279,
child: Text(
'번호',
style: TextStyle(
color: Colors.black.withOpacity(0.36000001430511475),
fontSize: 17,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 0,
),
),
),
Positioned(
left: 63,
top: 376,
child: Text(
'대/소문자,숫자,특수문자 8자리 이상',
style: TextStyle(
color: Colors.black.withOpacity(0.36000001430511475),
fontSize: 17,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 0,
),
),
),
Positioned(
left: 63,
top: 472,
child: Text(
'비밀번호를 확인하세요.',
style: TextStyle(
color: Colors.black.withOpacity(0.36000001430511475),
fontSize: 17,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 0,
),
),
),
Positioned(
left: 41,
top: 329,
child: SizedBox(
width: 82,
height: 23,
child: Text(
'비밀번호',
style: TextStyle(
color: Colors.black,
fontSize: 17,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
),
Positioned(
left: 41,
top: 425,
child: SizedBox(
width: 145,
height: 26,
child: Text(
'비밀번호 확인',
style: TextStyle(
color: Colors.black,
fontSize: 17,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
),
Positioned(
left: 43,
top: 235,
child: SizedBox(
width: 104,
height: 20,
child: Text(
'휴대폰 번호',
style: TextStyle(
color: Colors.black,
fontSize: 17,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
),
Positioned(
left: 115,
top: 291,
child: Container(
width: 100,
height: 100,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
),
),
Positioned(
left: 115,
top: 387,
child: Container(
width: 100,
height: 100,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
),
),
Positioned(
left: 72,
top: 631,
child: Container(
width: 305,
height: 51,
child: Stack(
children: [
Positioned(
left: 0,
top: 0,
child: Container(
width: 305,
height: 51,
decoration: ShapeDecoration(
color: Color(0xFFFEE201),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(25.50),
),
),
),
),
Positioned(
left: 17,
top: 11,
child: Container(
width: 31,
height: 30,
decoration: BoxDecoration(
image: DecorationImage(
image: NetworkImage("https://via.placeholder.com/31x30"),
fit: BoxFit.fill,
),
),
),
),
Positioned(
left: 88,
top: 17,
child: Text(
'카카오톡으로 로그인',
style: TextStyle(
color: Colors.black,
fontSize: 15,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
],
),
),
),
Positioned(
left: 72,
top: 706,
child: Container(
width: 305,
height: 51,
child: Stack(
children: [
Positioned(
left: 0,
top: 0,
child: Container(
width: 305,
height: 51,
decoration: ShapeDecoration(
color: Color(0xFF04C73C),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(25.50),
),
),
),
),
Positioned(
left: 17,
top: 10,
child: Container(
width: 33,
height: 32,
decoration: BoxDecoration(
image: DecorationImage(
image: NetworkImage("https://via.placeholder.com/33x32"),
fit: BoxFit.fill,
),
),
),
),
Positioned(
left: 102,
top: 17,
child: Text(
'네이버로 로그인',
style: TextStyle(
color: Colors.white,
fontSize: 15,
fontFamily: 'Inter',
fontWeight: FontWeight.w400,
height: 0,
),
),
),
],
),
),
),
Positioned(
left: 191,
top: 69,
child: Container(
width: 47,
height: 41,
decoration: BoxDecoration(
image: DecorationImage(
image: NetworkImage("https://via.placeholder.com/47x41"),
fit: BoxFit.fill,
),
),
),
),
],
),
),
],
);
}
}